---

- name: (Scored) check_1 Ensure the Log Config Module is Enabled
  shell: 'lsmod | egrep -i "cramfs|freevxfs|jffs2|hfs|hfsplus|udf"'
  register: filesystems_check
  failed_when: False

- name: (Scored) check_1.1.2 1.1.3 1.1.4 Ensure separate partition for /tmp and options
  shell: ' mount | grep "/tmp " '
  register: check_tmp
  failed_when: False

- name: (Scored) check_1.1.5 Ensure separate partition for /var
  shell: ' mount | grep "/var " '
  register: check_var
  failed_when: False

- name: (Scored) check_1.1.6 1.1.7 1.1.8 Ensure separate partition for /var/tmp
  shell: ' mount | grep "/var/tmp " '
  register: check_var_tmp
  failed_when: False

- name: (Scored) check_1.1.10 Ensure separate partition for /var/log
  shell: ' mount | grep "/var/log " '
  register: check_var_log
  failed_when: False

- name: (Scored) check_1.1.11 Ensure separate partition for /var/log/audit
  shell: ' mount | grep "/var/log/audit " '
  register: check_var_log_audit
  failed_when: False

- name: (Scored) check_1.1.12 Ensure separate partition for /home
  shell: ' mount | grep "/home " '
  register: check_home
  failed_when: False

#- name: debug check
#  debug:
#    var: filesystems_check

- name: "Create the final report of CIS Ubuntu Scored2 at {{ansible_date_time.date}}"
  template:
    src: CIS_Ubuntu_audit.j2
    dest: '/tmp/CIS_Ubuntu_benchmark.txt'
  delegate_to: localhost
  run_once: true

- name: CIS_HTTPD Benchmark output capture
  shell: "cat /tmp/CIS_Ubuntu_benchmark.txt"
  register: CIS_Ubuntu_report
  delegate_to: localhost
  run_once: true

- name: show me the patch report
  debug:
    var: CIS_Ubuntu_report.stdout
  delegate_to: localhost
  run_once: true

# Send the output to discord when we're ready

- name: Send something simple to sandbox server
  ansible_discord_webhook:
    webhook_url: "{{discord_webhook_url}}"
    content: "{{CIS_Ubuntu_report.stdout}}"
  when: discord_webhook_url is defined
  delegate_to: localhost
  run_once: true